version: "3.8"

services:
  redis:
    image: redis:7-alpine
    container_name: local-redis
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli",  "ping"]
      interval: 5s
      timeout: 3s
      retries: 10

  # опционально — веб UI
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: local-redis-commander
    environment:
      - REDIS_HOSTS=local:redis:6379:0
    ports:
      - "8081:8081"
    depends_on:
      - redis

volumes:
  redis_data:
